apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: memo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memo-app
    spec:
      containers:
      - name: memo-app
        image: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/t5-ecr:8781653762527caafa89e6c82465ed4a6e06ca5b
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: temp-storage
            mountPath: /mount  # 컨테이너 내부에서 /mount로 사용됨
      volumes:
        - name: temp-storage
          emptyDir: {}  # emptyDir 볼륨 사용
#          env:
#            - name: SPRING_DATASOURCE_URL
#              value: "jdbc:mysql://mysql-service:3306/app?serverTimezone=Asia/Seoul"
#            - name: SPRING_DATASOURCE_USERNAME
#              value: "app"
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: "app12345"

---
apiVersion: v1
kind: Service
metadata:
  name: memo-app-service
spec:
  selector:
    app.kubernetes.io/name: memo-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080 # 클러스터 내부에서 사용할 서비스 포트
      targetPort: 8080 # 서비스 전달 요청을 pod로 전달 포트
  # sessionAffinity: ClientIP
