apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: memo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memo-app
    spec:
      containers:
        - name: memo-app
          image: joe1534/memo-app:6c3cf463062d9bd01955cc83aebfbd233008612a
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          env:
#            - name: SPRING_DATASOURCE_URL
#              value: "jdbc:mysql://mysql-service:3306/app?serverTimezone=Asia/Seoul"
#            - name: SPRING_DATASOURCE_USERNAME
#              value: "app"
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: "app12345"