apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: memo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memo-app
    spec:
      containers:
        - name: memo-app
          image: joe1534/memo-app:096238d8ddeee62ef4017dcbf03284116d3c6b10
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          env:
#            - name: SPRING_DATASOURCE_URL
#              value: "jdbc:mysql://mysql-service:3306/app?serverTimezone=Asia/Seoul"
#            - name: SPRING_DATASOURCE_USERNAME
#              value: "app"
#            - name: SPRING_DATASOURCE_PASSWORD
#              value: "app12345"

---
apiVersion: v1
kind: Service
metadata:
  name: memo-app-service
spec:
  selector:
    app.kubernetes.io/name: memo-app
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31500 # 외부 접속 포트
      port: 8080 # 클러스터 내부에서 사용할 서비스 포트
      targetPort: 8080 # 서비스 전달 요청을 pod로 전달 포트
  sessionAffinity: ClientIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memo-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: memo.cj-cloud.site
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:061039804626:certificate/91dc2dda-42b1-4b0f-8f9d-027f49f27d42
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: 200-399
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
  - host: cj-cloud.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memo-app-service
            port:
              number: 8080 

  
