apiVersion: apps/v1
kind: Deployment
metadata:
  name: memo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memo-app
  template:
    metadata:
      labels:
        app: memo-app
    spec:
      containers:
        - name: memo-app
          image: ????/memo-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: memo-app-service
spec:
  selector:
    app: memo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
