name: Kubernetes-Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: image build
        run: docker build -t "${{ secrets.DOCKER_HUB_NAME }}"/memo-app:latest .

      - name: push
        run: docker push "${{ secrets.DOCKER_HUB_NAME }}"/memo-app:latest

      # local vm master node 에서 cat ~/.kube/config | base64 명령으로 인코딩한 결과값을 secrets.KUBECONFIG 값으로 인코딩후 액션에서 디코딩
      # - name: Kubeconfig
      #  run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Kubernetes distribution
        run: |
          kubectl apply -f k3s-Deploy.yaml
          kubectl rollout status deployment/memo-app
