name: Kubernetes-Deploy

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: image build
        run: docker build -t "${{ secrets.DOCKER_NAME }}"/memo-app:latest .

      - name: push
        run: docker push "${{ secrets.DOCKER_NAME }}"/memo-app:latest

      - name: Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Kubernetes distribution
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/memo-app
