name: Memo App CI/CD Workflow

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'manifest/**'
  workflow_dispatch:
    

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make Properties file
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
        shell: bash

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Rename jar file
        run: mv ./target/*.jar ./target/memo-app.jar

      - name: Check jar file
        run: ls -l ./target

      - uses: actions/upload-artifact@v4
        with:
          name: memo-app
          path: ./target/memo-app.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: ./Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

  argo_cd:
    runs-on: ubuntu-latest

    needs: ci

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ secrets.TOKEN }}

      - name: Update image in deployment manifest
        run: |
          sed -i "s%image: .*%image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}%" ./manifest/app/memo-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
          
          git add ./manifest/app/memo-deployment.yaml
          git commit -m "Update manifest deployment yaml file for ArgoCD"
          git push

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./manifest/app/memo-deployment.yaml
          kubectl apply -f ./manifest/app/memo-service.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
